comments:
  service: beaudar
  beaudar:
    repo: qvjp/qvjp.github.io
    branch: beaudar
    issue-term: pathname
    label: commentâœ¨ğŸ’¬âœ¨
    theme: preferred-color-scheme
    keep-theme: false
    crossorigin: anonymous


######## Sidebar ########
sidebar:
  menu:
    # post: '[btn.blog](/)'
    # wiki: '[btn.wiki](/wiki/)'
    # friends: '[å‹é“¾](/friends/)'
    # about: '[å…³äº](/about/)'
  # Sidebar widgets
  widget_layout:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: # /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: 'æ¬¢è¿ä½ ï¼š'
      content: |
        è¿™æ˜¯åˆä¸€ä¸ªæ“ä½œç³»ç»ŸåŸç†ä»‹ç»ã€ä»£ç å®ç°çš„ç½‘ç«™ï¼Œå°†é•¿æœŸç»´æŠ¤å¹¶ä¿æŒä½é¢‘æ›´æ–°ã€‚

article:
  # åˆ†ç±»é¢œè‰²
  category_color:
    'æ–°é—»ç¨¿': '#DA0F47'
    'è®¾è®¡å¼€å‘': '#03a9f4'
    'å¥‡æ€å¦™æƒ³': '#009688'
    'è§£å†³æ–¹æ¡ˆ': '#ff9800'
    'æŠ€æœ¯åŠ æ²¹ç«™': '#4caf50'
    'å¼€æºåº“': '#4caf50'
    'åšå®¢ä¸»é¢˜': '#ffa000'
    'åº”ç”¨ç¨‹åº': '#e91e63'
    'å®ç”¨è„šæœ¬': '#009688'
  share: [wechat, weibo, email, link]

style:
  codeblock:
    scrollbar: 0px